//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFP_QuanLyNhanVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhân_Viên
    {
        public int Mã_Nhân_Viên { get; set; }
        public string Tên_Nhân_Viên { get; set; }
        public Nullable<int> Năm_Sinh { get; set; }
        public Nullable<double> Lương { get; set; }
        public string Nhóm_Máu { get; set; }
        public Nullable<bool> Giới_Tính { get; set; }
        public string Ảnh { get; set; }
    }
}
